### ISSUE TITLE
Version 2.0.0.beta1 not working with Vaadin 14.0.1

### ISSUE THREAD

**Issue by ugurdoksan** [appreciated/grid-layout#4]
**Code:** Demo Code
**Application Server:** Tomcat 9.0 or Jetty
**Vaadin Version:** 14.0.1
Grid Layout Version: 2.0.0.beta1
Browser: Any browser with the latest version (Windows)

Note: There is not any error on the screen or on the browser console. There is only a blank window.

**Comment by ugurdoksan** [comment]
Same situation with https://github.com/appreciated/apexcharts-flow/issues/28

**Comment by appreciated** [comment]
@ugurdoksan are you using the compatiblity mode?

**Comment by ugurdoksan** [comment]
@appreciated Yes, I am using flow-server-compatibility-mode dependency.

**Comment by appreciated** [comment]
Yeah the compatiblity is not supported. Please check your setup, the reason why you are not seeing any exception has something to do with it. 
[You should see an exception similar to this one.](https://github.com/appreciated/vaadin-app-layout/issues/285)
