### ISSUE TITLE
Couldn't find the definition of the element with tag 'grid-layout'

### ISSUE THREAD

**Issue by jeemsk** [appreciated/grid-layout#5]
Hi, im using the new version of vaadin with npm and spring in Intellij Idea, but when i put the maven installation in pom file.

When i run, i recive this message

i have this in may YML 

vaadin:
    compatibilityMode : false

Couldn't find the definition of the element with tag 'grid-layout' in any template file declared using '@JsModule'

**Comment by appreciated** [comment]
@jeemsk sorry you are having issues. I've just tried using it with a fresh spring-boot starter from vaadin.com but didn't have any issues using it. 
Which starter vaadin and addon version are you using?

**Comment by appreciated** [comment]
Glad you managed to figured it out! Sorry for my late Response

**Comment by maksimu** [comment]
@jeemsk 
> Thanks, i see my error. I have a differents dependencies versions. Thaks a lot

What was the difference in your dependency versions? I'm having the same issue but don't see what version to change.
